import type { Anime, Episode } from '@/types';

// Helper function to generate episodes for an anime
function generateEpisodes(animeId: string, count: number, titles: string[], is4K: boolean = false, is4K240: boolean = false): Episode[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `${animeId}-ep-${i + 1}`,
    animeId,
    number: i + 1,
    title: titles[i] || `Episode ${i + 1}`,
    duration: 24,
    is4KEnhanced: is4K,
    is4K240: is4K240,
    thumbnail: `https://img.anili.st/media/${animeId}`,
  }));
}

// Episode titles for each anime
const attackOnTitanEpisodes = [
  'To You, in 2000 Years: The Fall of Shiganshina, Part 1',
  'That Day: The Fall of Shiganshina, Part 2',
  'A Dim Light Amid Despair: Humanity\'s Comeback, Part 1',
  'The Night of the Closing Ceremony: Humanity\'s Comeback, Part 2',
  'First Battle: The Struggle for Trost, Part 1',
  'The World the Girl Saw: The Struggle for Trost, Part 2',
  'Small Blade: The Struggle for Trost, Part 3',
  'I Can Hear His Heartbeat: The Struggle for Trost, Part 4',
  'Whereabouts of His Left Arm: The Struggle for Trost, Part 5',
  'Response: The Struggle for Trost, Part 6',
  'Idol: The Struggle for Trost, Part 7',
  'Wound: The Struggle for Trost, Part 8',
  'Primal Desire: The Struggle for Trost, Part 9',
  'Can\'t Look into His Eyes Yet: Eve of the Counterattack, Part 1',
  'Special Operations Squad: Eve of the Counterattack, Part 2',
  'What Needs to be Done Now: Eve of the Counterattack, Part 3',
  'Female Titan: The 57th Exterior Scouting Mission, Part 1',
  'Forest of Giant Trees: The 57th Exterior Scouting Mission, Part 2',
  'Bite: The 57th Exterior Scouting Mission, Part 3',
  'Erwin Smith: The 57th Exterior Scouting Mission, Part 4',
  'Crushing Blow: The 57th Exterior Scouting Mission, Part 5',
  'The Defeated: The 57th Exterior Scouting Mission, Part 6',
  'Smile: Assault on Stohess, Part 1',
  'Mercy: Assault on Stohess, Part 2',
  'Wall: Assault on Stohess, Part 3',
];

const myHeroAcademiaEpisodes = [
  'Izuku Midoriya: Origin',
  'What It Takes to Be a Hero',
  'Roaring Muscles',
  'Start Line',
  'What I Can Do for Now',
  'Rage, You Damned Nerd',
  'Deku vs. Kacchan',
  'Bakugo\'s Start Line',
  'Yeah, Just Do Your Best, Ida!',
  'Encounter with the Unknown',
  'Game Over',
  'All Might',
  'In Each of Our Hearts',
];

const onePunchManEpisodes = [
  'The Strongest Man',
  'The Lone Cyborg',
  'The Obsessive Scientist',
  'The Modern Ninja',
  'The Ultimate Master',
  'The Terrifying City',
  'The Ultimate Disciple',
  'The Deep Sea King',
  'Unyielding Justice',
  'Unparalleled Peril',
  'The Dominator of the Universe',
  'The Strongest Hero',
];

const demonSlayerEpisodes = [
  'Cruelty',
  'Trainer Sakonji Urokodaki',
  'Sabito and Makomo',
  'Final Selection',
  'My Own Steel',
  'Swordsman Accompanying a Demon',
  'Muzan Kibutsuji',
  'The Smell of Enchanting Blood',
  'Temari Demon and Arrow Demon',
  'Together Forever',
  'Tsuzumi Mansion',
  'The Boar Bares Its Fangs, Zenitsu Sleeps',
  'Something More Important Than Life',
  'The House with the Wisteria Family Crest',
  'Mount Natagumo',
  'Letting Someone Else Go First',
  'You Must Master a Single Thing',
  'A Forged Bond',
  'Hinokami',
  'Pretend Family',
  'Against Corps Rules',
  'Master of the Mansion',
  'Hashira Meeting',
  'Rehabilitation Training',
  'Tsuguko, Kanao Tsuyuri',
  'New Mission',
];

const jujutsuKaisenEpisodes = [
  'Ryomen Sukuna',
  'For Myself',
  'Girl of Steel',
  'Curse Womb Must Die',
  'Curse Womb Must Die -II-',
  'After Rain',
  'Assault',
  'Boredom',
  'Small Fry and Reverse Retribution',
  'Idle Transfiguration',
  'Narrow-minded',
  'To You, Someday',
  'Tomorrow',
  'Kyoto Sister School Exchange Event - Group Battle 0',
  'Kyoto Sister School Exchange Event - Group Battle 1',
  'Kyoto Sister School Exchange Event - Group Battle 2',
  'Kyoto Sister School Exchange Event - Group Battle 3',
  'Sage',
  'Black Flash',
  'Nonstandard',
  'Jujutsu Koshien',
  'The Origin of Blind Obedience',
  'The Origin of Blind Obedience -II-',
  'Accomplices',
];

const narutoEpisodes = [
  'Enter: Naruto Uzumaki!',
  'My Name is Konohamaru!',
  'Sasuke and Sakura: Friends or Foes?',
  'Pass or Fail: Survival Test',
  'You Failed! Kakashi\'s Final Decision',
  'A Dangerous Mission! Journey to the Land of Waves!',
  'The Assassin of the Mist!',
  'The Oath of Pain',
  'Kakashi: Sharingan Warrior',
  'The Forest of Chakra',
  'The Land Where a Hero Once Lived',
  'Battle on the Bridge! Zabuza Returns!',
  'Haku\'s Secret Jutsu: Crystal Ice Mirrors',
  'The Number One Hyperactive, Knucklehead Ninja Joins the Fight!',
  'Zero Visibility: The Sharingan Shatters',
  'The Broken Seal',
  'White Past: Hidden Ambition',
  'The Weapons Known as Shinobi',
  'The Demon in the Snow',
  'A New Chapter Begins: The Chunin Exam!',
  'Identify Yourself: Powerful New Rivals',
  'Chunin Challenge: Rock Lee vs. Sasuke!',
  'Genin Takedown! All Nine Rookies Face Off!',
  'Start Your Engines: The Chunin Exam Begins!',
];

const onePieceEpisodes = [
  'I\'m Luffy! The Man Who Will Become the Pirate King!',
  'The Great Swordsman Appears! Pirate Hunter, Roronoa Zoro',
  'Morgan vs. Luffy! Who\'s This Beautiful Young Girl?',
  'Luffy\'s Past! The Red-Haired Shanks Appears!',
  'Fear, Mysterious Power! Pirate Clown Captain Buggy!',
  'Desperate Situation! Beast Tamer Mohji vs. Luffy!',
  'Grand Duel! Zoro the Swordsman vs. Cabaji the Acrobat!',
  'Who Will Win? Showdown Between the True Powers of the Devil!',
  'The Honorable Liar? Captain Usopp!',
  'The Weirdest Guy Ever! Jango the Hypnotist!',
  'Expose the Plot! Pirate Butler, Captain Kuro!',
  'Clash with the Black Cat Pirates! The Great Battle on the Slope!',
  'The Terrifying Duo! Meowban Brothers vs. Zoro!',
  'Luffy Back in Action! Miss Kaya\'s Desperate Resistance!',
  'Beat Kuro! Usopp the Man\'s Tearful Resolve!',
  'Protect Kaya! The Usopp Pirates\' Great Efforts!',
  'Anger Explosion! Kuro vs. Luffy! How It Ends!',
  'You\'re the Weird Creature! Gaimon and His Strange Friends!',
  'The Three-Sword Style\'s Past! Zoro and Kuina\'s Vow!',
  'Famous Cook! Sanji of the Sea Restaurant!',
  'Unwelcome Customer! Sanji\'s Food and Gin\'s Debt!',
  'The Strongest Pirate Fleet! Commodore Don Krieg!',
  'Protect Baratie! The Great Pirate, Red Foot Zeff!',
  'Hawk-Eye Mihawk! The Great Swordsman Zoro Falls At Sea!',
];

const deathNoteEpisodes = [
  'Rebirth',
  'Confrontation',
  'Dealings',
  'Pursuit',
  'Tactics',
  'Unraveling',
  'Overcast',
  'Glare',
  'Encounter',
  'Doubt',
  'Assault',
  'Love',
  'Confession',
  'Friend',
  'Wager',
  'Decision',
  'Execution',
  'Ally',
  'Matsuda',
  'Makeshift',
  'Performance',
  'Guidance',
  'Frenzy',
  'Revival',
  'Silence',
  'Renewal',
  'Abduction',
  'Impatience',
  'Father',
  'Justice',
  'Transfer',
  'Selection',
  'Scorn',
  'Vigilance',
  '1.28',
  'New World',
  'The Last Day',
];

const hunterXHunterEpisodes = [
  'Departure × And × Friends',
  'Test × Of × Tests',
  'Rivals × For × Survival',
  'Hope × And × Ambition',
  'Hisoka × Is × Sneaky',
  'A × Surprising × Challenge',
  'Showdown × On × The Airship',
  'Decision × By × Majority?',
  'Beware × Of × Prisoners',
  'Trick × To × The Trick',
  'Trouble × With × The Gamble',
  'Last × Test × Of × Resolve',
  'Letter × From × Gon',
  'Hit × The × Target',
  'Explosion × Of × Deception',
  'Defeat × And × Disgrace',
  'Trap × In × The Hole',
  'Big × Time × Interview',
  'Can\'t See × If × You\'re Blind',
  'Baffling × Turn × Of × Events',
  'Some × Brother × Trouble',
  'A × Dangerous × Watchdog',
  'The × Guard\'s ×ستand',
  'The × Zoldyck × Family',
];

const yourNameEpisodes = [
  'Your Name. (Full Movie)',
];

const steinsGateEpisodes = [
  'Prologue of the Beginning and End',
  'Time Travel Paranoia',
  'Parallel World Paranoia',
  'Interpreter Rendezvous',
  'Starmine Rendezvous',
  'Butterfly Effect\'s Divergence',
  'Divergence Singularity',
  'Chaos Theory Homeostasis I',
  'Chaos Theory Homeostasis II',
  'Chaos Theory Homeostasis III',
  'Dogma in Event Horizon',
  'Dogma in Ergosphere',
  'Metaphysics Necrosis',
  'Physical Necrosis',
  'Missing Link Necrosis',
  'Sacrificial Necrosis',
  'Made in Complex',
  'Fractal Androgynous',
  'Endless Apoptosis',
  'Finalize Apoptosis',
  'Paradox Meltdown',
  'Being Meltdown',
  'Open the Steins Gate',
  'Achievement Point',
];

const fmabEpisodes = [
  'Fullmetal Alchemist',
  'The First Day',
  'City of Heresy',
  'An Alchemist\'s Anguish',
  'Rain of Sorrows',
  'Road of Hope',
  'Hidden Truths',
  'The Fifth Laboratory',
  'Created Feelings',
  'Separate Destinations',
  'Miracle at Rush Valley',
  'One is All, All is One',
  'Beasts of Dublith',
  'Those Who Lurk Underground',
  'Envoy from the East',
  'Footsteps of a Comrade-in-Arms',
  'Cold Flame',
  'The Arrogant Palm of a Small Human',
  'Death of the Undying',
  'Father Before the Grave',
  'Advance of the Fool',
  'Backs in the Distance',
  'Girl on the Battlefield',
  'Inside the Belly',
  'Doorway of Darkness',
  'Reunion',
  'Interlude Party',
  'Father',
  'Struggle of the Fool',
  'The Ishvalan War of Extermination',
  'The 520 Cens Promise',
  'The Fuhrer\'s Son',
  'The Northern Wall of Briggs',
  'Ice Queen',
  'The Shape of This Country',
  'Family Portrait',
  'The First Homunculus',
  'Conflict at Baschool',
  'Daydream',
  'Homunculus (The Dwarf in the Flask)',
  'The Abyss',
  'Signs of a Counteroffensive',
  'Bite of the Ant',
  'Revving at Full Throttle',
  'The Promised Day',
  'Looming Shadows',
  'Emissary of Darkness',
  'The Oath in the Tunnel',
  'Filial Affection',
  'Upheaval in Central',
  'The Immortal Legion',
  'Combined Strength',
  'Flame of Vengeance',
  'Beyond the Inferno',
  'The Adults\' Way of Life',
  'The Return of the Fuhrer',
  'Eternal Leave',
  'Sacrifices',
  'Lost Light',
  'Eye of Heaven, Gateway of Earth',
  'He Who Would Swallow God',
  'A Fierce Counterattack',
  'The Other Side of the Gateway',
  'Journey\'s End',
];

// Mock anime data for development/demo purposes
export const mockAnimeData: Anime[] = [
  {
    id: '16498',
    anilistId: 16498,
    titleEnglish: 'Attack on Titan',
    titleRomaji: 'Shingeki no Kyojin',
    titleNative: '進撃の巨人',
    synopsis: 'Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneG.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2013,
    episodeCount: 25,
    duration: 24,
    averageScore: 85,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '2', name: 'Drama', slug: 'drama' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '1', name: 'Wit Studio', isMain: true }],
    episodes: generateEpisodes('16498', 25, attackOnTitanEpisodes, true, true),
  },
  {
    id: '21459',
    anilistId: 21459,
    titleEnglish: 'My Hero Academia',
    titleRomaji: 'Boku no Hero Academia',
    titleNative: '僕のヒーローアカデミア',
    synopsis: 'What would the world be like if 80 percent of the population manifested superpowers called "Quirks"? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study?',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-DUKLgasrgeNO.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-yeVkolGKdGUV.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2016,
    episodeCount: 13,
    duration: 24,
    averageScore: 77,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
    ],
    studios: [{ id: '2', name: 'Bones', isMain: true }],
    episodes: generateEpisodes('21459', 13, myHeroAcademiaEpisodes, true, false),
  },
  {
    id: '21087',
    anilistId: 21087,
    titleEnglish: 'One Punch Man',
    titleRomaji: 'One Punch Man',
    titleNative: 'ワンパンマン',
    synopsis: 'Saitama has a rather peculiar hobby, being a superhero, but despite his heroic deeds and all the praise he has received, he feels empty. After three years of special training, he has become so powerful that he can defeat any enemy with a single punch.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-UV2tu6exrfXz.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sHb9zUZFsHe1.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2015,
    episodeCount: 12,
    duration: 24,
    averageScore: 83,
    popularity: 450000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
      { id: '5', name: 'Sci-Fi', slug: 'sci-fi' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
    episodes: generateEpisodes('21087', 12, onePunchManEpisodes, true, true),
  },
  {
    id: '101922',
    anilistId: 101922,
    titleEnglish: 'Demon Slayer: Kimetsu no Yaiba',
    titleRomaji: 'Kimetsu no Yaiba',
    titleNative: '鬼滅の刃',
    synopsis: 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YfZhKBUDDS6L.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2019,
    episodeCount: 26,
    duration: 24,
    averageScore: 86,
    popularity: 600000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '4', name: 'ufotable', isMain: true }],
    episodes: generateEpisodes('101922', 26, demonSlayerEpisodes, true, true),
  },
  {
    id: '113415',
    anilistId: 113415,
    titleEnglish: 'Jujutsu Kaisen',
    titleRomaji: 'Jujutsu Kaisen',
    titleNative: '呪術廻戦',
    synopsis: 'Yuji Itadori is an unnaturally fit high school student living in Sendai. On the day his grandfather dies, he encounters a cursed object and decides to swallow it to protect his friends, becoming a vessel for Sukuna, the King of Curses.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2020,
    episodeCount: 24,
    duration: 24,
    averageScore: 86,
    popularity: 550000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '5', name: 'MAPPA', isMain: true }],
    episodes: generateEpisodes('113415', 24, jujutsuKaisenEpisodes, true, true),
  },
  {
    id: '20',
    anilistId: 20,
    titleEnglish: 'Naruto',
    titleRomaji: 'Naruto',
    titleNative: 'ナルト',
    synopsis: 'Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village\'s leader and strongest ninja.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-LxrhhIQyiE60.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2002,
    episodeCount: 220,
    duration: 23,
    averageScore: 79,
    popularity: 350000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
    ],
    studios: [{ id: '6', name: 'Pierrot', isMain: true }],
    episodes: generateEpisodes('20', 24, narutoEpisodes, true, false),
  },
  {
    id: '21',
    anilistId: 21,
    titleEnglish: 'One Piece',
    titleRomaji: 'One Piece',
    titleNative: 'ワンピース',
    synopsis: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. His capture and execution by the World Government brought a change throughout the world.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-YCDoj1EkAxFn.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg',
    status: 'RELEASING',
    format: 'TV',
    season: 'FALL',
    seasonYear: 1999,
    episodeCount: 1100,
    duration: 24,
    averageScore: 88,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
    ],
    studios: [{ id: '7', name: 'Toei Animation', isMain: true }],
    episodes: generateEpisodes('21', 24, onePieceEpisodes, true, false),
  },
  {
    id: '1535',
    anilistId: 1535,
    titleEnglish: 'Death Note',
    titleRomaji: 'Death Note',
    titleNative: 'デスノート',
    synopsis: 'Light Yagami is an ace student with great prospects—and he\'s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCwhzhi96X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2006,
    episodeCount: 37,
    duration: 23,
    averageScore: 84,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '8', name: 'Mystery', slug: 'mystery' },
      { id: '9', name: 'Psychological', slug: 'psychological' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
    episodes: generateEpisodes('1535', 37, deathNoteEpisodes, true, true),
  },
  {
    id: '11061',
    anilistId: 11061,
    titleEnglish: 'Hunter x Hunter (2011)',
    titleRomaji: 'Hunter x Hunter (2011)',
    titleNative: 'ハンター×ハンター (2011)',
    synopsis: 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father, who left him when he was younger.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-NpIIobuQNbJW.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2011,
    episodeCount: 148,
    duration: 24,
    averageScore: 89,
    popularity: 450000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
    episodes: generateEpisodes('11061', 24, hunterXHunterEpisodes, true, true),
  },
  {
    id: '21519',
    anilistId: 21519,
    titleEnglish: 'Your Name.',
    titleRomaji: 'Kimi no Na wa.',
    titleNative: '君の名は。',
    synopsis: 'Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-fPhvy69vnQqS.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg',
    status: 'FINISHED',
    format: 'MOVIE',
    seasonYear: 2016,
    duration: 106,
    averageScore: 85,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '2', name: 'Drama', slug: 'drama' },
      { id: '10', name: 'Romance', slug: 'romance' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '8', name: 'CoMix Wave Films', isMain: true }],
    episodes: generateEpisodes('21519', 1, yourNameEpisodes, true, true),
  },
  {
    id: '9253',
    anilistId: 9253,
    titleEnglish: 'Steins;Gate',
    titleRomaji: 'Steins;Gate',
    titleNative: 'シュタインズ・ゲート',
    synopsis: 'Rintaro Okabe is a self-proclaimed "mad scientist" who believes that an international scientific organization named SERN is conspiring to reshape the world according to its own interests.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9253-7pdcVzQSkKxT.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/9253-1LU8ZFPYg9pZ.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2011,
    episodeCount: 24,
    duration: 24,
    averageScore: 89,
    popularity: 350000,
    isAdult: false,
    genres: [
      { id: '5', name: 'Sci-Fi', slug: 'sci-fi' },
      { id: '8', name: 'Mystery', slug: 'mystery' },
      { id: '9', name: 'Psychological', slug: 'psychological' },
    ],
    studios: [{ id: '9', name: 'White Fox', isMain: true }],
    episodes: generateEpisodes('9253', 24, steinsGateEpisodes, true, false),
  },
  {
    id: '5114',
    anilistId: 5114,
    titleEnglish: 'Fullmetal Alchemist: Brotherhood',
    titleRomaji: 'Hagane no Renkinjutsushi: Fullmetal Alchemist',
    titleNative: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    synopsis: 'After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-KJTQz9AIm6Wk.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2009,
    episodeCount: 64,
    duration: 24,
    averageScore: 91,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '2', name: 'Bones', isMain: true }],
    episodes: generateEpisodes('5114', 64, fmabEpisodes, true, true),
  },
];

export function getMockAnimeById(id: string | number): Anime | undefined {
  const stringId = String(id);
  return mockAnimeData.find(a => a.id === stringId || String(a.anilistId) === stringId);
}

export function getMockAnimeList(limit: number = 12): Anime[] {
  return mockAnimeData.slice(0, limit);
}

export function searchMockAnime(query: string): Anime[] {
  const lowerQuery = query.toLowerCase();
  return mockAnimeData.filter(anime =>
    anime.titleEnglish?.toLowerCase().includes(lowerQuery) ||
    anime.titleRomaji?.toLowerCase().includes(lowerQuery) ||
    anime.titleNative?.includes(query)
  );
}

export function getMockAnimeByGenre(genre: string): Anime[] {
  return mockAnimeData.filter(anime =>
    anime.genres?.some(g => g.name.toLowerCase() === genre.toLowerCase())
  );
}

export function getMockEpisodeById(animeId: string, episodeNumber: number): Episode | undefined {
  const anime = getMockAnimeById(animeId);
  return anime?.episodes?.find(ep => ep.number === episodeNumber);
}
