import type { Anime } from '@/types';

// Mock anime data for development/demo purposes
export const mockAnimeData: Anime[] = [
  {
    id: '1',
    anilistId: 16498,
    titleEnglish: 'Attack on Titan',
    titleRomaji: 'Shingeki no Kyojin',
    titleNative: '進撃の巨人',
    synopsis: 'Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneG.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2013,
    episodeCount: 25,
    duration: 24,
    averageScore: 85,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '2', name: 'Drama', slug: 'drama' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '1', name: 'Wit Studio', isMain: true }],
  },
  {
    id: '2',
    anilistId: 21459,
    titleEnglish: 'My Hero Academia',
    titleRomaji: 'Boku no Hero Academia',
    titleNative: '僕のヒーローアカデミア',
    synopsis: 'What would the world be like if 80 percent of the population manifested superpowers called "Quirks"? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study?',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-DUKLgasrgeNO.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-yeVkolGKdGUV.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2016,
    episodeCount: 13,
    duration: 24,
    averageScore: 77,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
    ],
    studios: [{ id: '2', name: 'Bones', isMain: true }],
  },
  {
    id: '3',
    anilistId: 20958,
    titleEnglish: 'One Punch Man',
    titleRomaji: 'One Punch Man',
    titleNative: 'ワンパンマン',
    synopsis: 'Saitama has a rather peculiar hobby, being a superhero, but despite his heroic deeds and all the praise he has received, he feels empty. After three years of special training, he has become so powerful that he can defeat any enemy with a single punch.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-UV2tu6exrfXz.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sHb9zUZFsHe1.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2015,
    episodeCount: 12,
    duration: 24,
    averageScore: 83,
    popularity: 450000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
      { id: '5', name: 'Sci-Fi', slug: 'sci-fi' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
  },
  {
    id: '4',
    anilistId: 101922,
    titleEnglish: 'Demon Slayer: Kimetsu no Yaiba',
    titleRomaji: 'Kimetsu no Yaiba',
    titleNative: '鬼滅の刃',
    synopsis: 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YfZhKBUDDS6L.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2019,
    episodeCount: 26,
    duration: 24,
    averageScore: 86,
    popularity: 600000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '4', name: 'ufotable', isMain: true }],
  },
  {
    id: '5',
    anilistId: 113415,
    titleEnglish: 'Jujutsu Kaisen',
    titleRomaji: 'Jujutsu Kaisen',
    titleNative: '呪術廻戦',
    synopsis: 'Yuji Itadori is an unnaturally fit high school student living in Sendai. On the day his grandfather dies, he encounters a cursed object and decides to swallow it to protect his friends, becoming a vessel for Sukuna, the King of Curses.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2020,
    episodeCount: 24,
    duration: 24,
    averageScore: 86,
    popularity: 550000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '5', name: 'MAPPA', isMain: true }],
  },
  {
    id: '6',
    anilistId: 20,
    titleEnglish: 'Naruto',
    titleRomaji: 'Naruto',
    titleNative: 'ナルト',
    synopsis: 'Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village\'s leader and strongest ninja.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-LxrhhIQyiE60.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2002,
    episodeCount: 220,
    duration: 23,
    averageScore: 79,
    popularity: 350000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
    ],
    studios: [{ id: '6', name: 'Pierrot', isMain: true }],
  },
  {
    id: '7',
    anilistId: 21,
    titleEnglish: 'One Piece',
    titleRomaji: 'One Piece',
    titleNative: 'ワンピース',
    synopsis: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. His capture and execution by the World Government brought a change throughout the world.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-YCDoj1EkAxFn.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg',
    status: 'RELEASING',
    format: 'TV',
    season: 'FALL',
    seasonYear: 1999,
    episodeCount: 1100,
    duration: 24,
    averageScore: 88,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '4', name: 'Comedy', slug: 'comedy' },
    ],
    studios: [{ id: '7', name: 'Toei Animation', isMain: true }],
  },
  {
    id: '8',
    anilistId: 1535,
    titleEnglish: 'Death Note',
    titleRomaji: 'Death Note',
    titleNative: 'デスノート',
    synopsis: 'Light Yagami is an ace student with great prospects—and he\'s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCwhzhi96X.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2006,
    episodeCount: 37,
    duration: 23,
    averageScore: 84,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '8', name: 'Mystery', slug: 'mystery' },
      { id: '9', name: 'Psychological', slug: 'psychological' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
  },
  {
    id: '9',
    anilistId: 11061,
    titleEnglish: 'Hunter x Hunter (2011)',
    titleRomaji: 'Hunter x Hunter (2011)',
    titleNative: 'ハンター×ハンター (2011)',
    synopsis: 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father, who left him when he was younger.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-NpIIobuQNbJW.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'FALL',
    seasonYear: 2011,
    episodeCount: 148,
    duration: 24,
    averageScore: 89,
    popularity: 450000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '3', name: 'Madhouse', isMain: true }],
  },
  {
    id: '10',
    anilistId: 21519,
    titleEnglish: 'Your Name.',
    titleRomaji: 'Kimi no Na wa.',
    titleNative: '君の名は。',
    synopsis: 'Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-fPhvy69vnQqS.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg',
    status: 'FINISHED',
    format: 'MOVIE',
    seasonYear: 2016,
    duration: 106,
    averageScore: 85,
    popularity: 400000,
    isAdult: false,
    genres: [
      { id: '2', name: 'Drama', slug: 'drama' },
      { id: '10', name: 'Romance', slug: 'romance' },
      { id: '6', name: 'Supernatural', slug: 'supernatural' },
    ],
    studios: [{ id: '8', name: 'CoMix Wave Films', isMain: true }],
  },
  {
    id: '11',
    anilistId: 9253,
    titleEnglish: 'Steins;Gate',
    titleRomaji: 'Steins;Gate',
    titleNative: 'シュタインズ・ゲート',
    synopsis: 'Rintaro Okabe is a self-proclaimed "mad scientist" who believes that an international scientific organization named SERN is conspiring to reshape the world according to its own interests.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9253-7pdcVzQSkKxT.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/9253-1LU8ZFPYg9pZ.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2011,
    episodeCount: 24,
    duration: 24,
    averageScore: 89,
    popularity: 350000,
    isAdult: false,
    genres: [
      { id: '5', name: 'Sci-Fi', slug: 'sci-fi' },
      { id: '8', name: 'Mystery', slug: 'mystery' },
      { id: '9', name: 'Psychological', slug: 'psychological' },
    ],
    studios: [{ id: '9', name: 'White Fox', isMain: true }],
  },
  {
    id: '12',
    anilistId: 5114,
    titleEnglish: 'Fullmetal Alchemist: Brotherhood',
    titleRomaji: 'Hagane no Renkinjutsushi: Fullmetal Alchemist',
    titleNative: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    synopsis: 'After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality.',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-KJTQz9AIm6Wk.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg',
    status: 'FINISHED',
    format: 'TV',
    season: 'SPRING',
    seasonYear: 2009,
    episodeCount: 64,
    duration: 24,
    averageScore: 91,
    popularity: 500000,
    isAdult: false,
    genres: [
      { id: '1', name: 'Action', slug: 'action' },
      { id: '7', name: 'Adventure', slug: 'adventure' },
      { id: '3', name: 'Fantasy', slug: 'fantasy' },
    ],
    studios: [{ id: '2', name: 'Bones', isMain: true }],
  },
];

export function getMockAnimeById(id: string | number): Anime | undefined {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return mockAnimeData.find(a => a.id === String(numId) || a.anilistId === numId);
}

export function getMockAnimeList(limit: number = 12): Anime[] {
  return mockAnimeData.slice(0, limit);
}

export function searchMockAnime(query: string): Anime[] {
  const lowerQuery = query.toLowerCase();
  return mockAnimeData.filter(anime =>
    anime.titleEnglish?.toLowerCase().includes(lowerQuery) ||
    anime.titleRomaji?.toLowerCase().includes(lowerQuery) ||
    anime.titleNative?.includes(query)
  );
}

export function getMockAnimeByGenre(genre: string): Anime[] {
  return mockAnimeData.filter(anime =>
    anime.genres?.some(g => g.name.toLowerCase() === genre.toLowerCase())
  );
}
